kind: pipeline
name: default

steps:
- name: publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
    distributions:
    - sdist
    - bdist_wheel
  when:
    ref:
    - refs/tags/*.*.*
